- name: Basename of an HTTP url
  gather_facts: no
  hosts: localhost
  tasks:
  - block:
    - debug:
        var: basename
    - debug:
        var: filename
    - assert:
        that:
        - basename == "fedora-coreos-35.20211203.3.0-qemu.x86_64.qcow2.xz"
        - filename == "fedora-coreos-35.20211203.3.0-qemu.x86_64.qcow2"
    vars:
      basename: "{{ input|basename }}"
      filename: "{{ basename|splitext|first }}"
      input: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/35.20211203.3.0/x86_64/fedora-coreos-35.20211203.3.0-qemu.x86_64.qcow2.xz
